export const initState = {
  user: {},
  categories: [],
  error: '',
  errorReg: '',
  cart: [],
  product: [],
  myProduct: [],
  sub: [],
  comments: [],
  waitingList: [],
  waitingListToSend: [],
  doneSending: [],
  receiptProducts: [],
  rating: 0,
  seller : {},
};
